// Code generated by go-enum DO NOT EDIT.
// Version: v0.9.1

// Built By: go install

package main

import (
	"errors"
	"fmt"
)

const (
	// AccessLevelNone is a AccessLevel of type None.
	AccessLevelNone AccessLevel = 0
	// AccessLevelRehabber is a AccessLevel of type Rehabber.
	AccessLevelRehabber AccessLevel = 1
	// AccessLevelCoordinator is a AccessLevel of type Coordinator.
	AccessLevelCoordinator AccessLevel = 2
	// AccessLevelAdmin is a AccessLevel of type Admin.
	AccessLevelAdmin AccessLevel = 3
)

var ErrInvalidAccessLevel = errors.New("not a valid AccessLevel")

const _AccessLevelName = "NoneRehabberCoordinatorAdmin"

// AccessLevelValues returns a list of the values for AccessLevel
func AccessLevelValues() []AccessLevel {
	return []AccessLevel{
		AccessLevelNone,
		AccessLevelRehabber,
		AccessLevelCoordinator,
		AccessLevelAdmin,
	}
}

var _AccessLevelMap = map[AccessLevel]string{
	AccessLevelNone:        _AccessLevelName[0:4],
	AccessLevelRehabber:    _AccessLevelName[4:12],
	AccessLevelCoordinator: _AccessLevelName[12:23],
	AccessLevelAdmin:       _AccessLevelName[23:28],
}

// String implements the Stringer interface.
func (x AccessLevel) String() string {
	if str, ok := _AccessLevelMap[x]; ok {
		return str
	}
	return fmt.Sprintf("AccessLevel(%d)", x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x AccessLevel) IsValid() bool {
	_, ok := _AccessLevelMap[x]
	return ok
}

var _AccessLevelValue = map[string]AccessLevel{
	_AccessLevelName[0:4]:   AccessLevelNone,
	_AccessLevelName[4:12]:  AccessLevelRehabber,
	_AccessLevelName[12:23]: AccessLevelCoordinator,
	_AccessLevelName[23:28]: AccessLevelAdmin,
}

// ParseAccessLevel attempts to convert a string to a AccessLevel.
func ParseAccessLevel(name string) (AccessLevel, error) {
	if x, ok := _AccessLevelValue[name]; ok {
		return x, nil
	}
	return AccessLevel(0), fmt.Errorf("%s is %w", name, ErrInvalidAccessLevel)
}
