// Code generated by go-enum DO NOT EDIT.
// Version: v0.9.1

// Built By: go install

package main

import (
	"errors"
	"fmt"
)

const (
	// TimePreferenceNone is a TimePreference of type None.
	TimePreferenceNone TimePreference = 0
	// TimePreferenceNewer is a TimePreference of type Newer.
	TimePreferenceNewer TimePreference = 1
	// TimePreferenceOlder is a TimePreference of type Older.
	TimePreferenceOlder TimePreference = 2
)

var ErrInvalidTimePreference = errors.New("not a valid TimePreference")

const _TimePreferenceName = "NoneNewerOlder"

// TimePreferenceValues returns a list of the values for TimePreference
func TimePreferenceValues() []TimePreference {
	return []TimePreference{
		TimePreferenceNone,
		TimePreferenceNewer,
		TimePreferenceOlder,
	}
}

var _TimePreferenceMap = map[TimePreference]string{
	TimePreferenceNone:  _TimePreferenceName[0:4],
	TimePreferenceNewer: _TimePreferenceName[4:9],
	TimePreferenceOlder: _TimePreferenceName[9:14],
}

// String implements the Stringer interface.
func (x TimePreference) String() string {
	if str, ok := _TimePreferenceMap[x]; ok {
		return str
	}
	return fmt.Sprintf("TimePreference(%d)", x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x TimePreference) IsValid() bool {
	_, ok := _TimePreferenceMap[x]
	return ok
}

var _TimePreferenceValue = map[string]TimePreference{
	_TimePreferenceName[0:4]:  TimePreferenceNone,
	_TimePreferenceName[4:9]:  TimePreferenceNewer,
	_TimePreferenceName[9:14]: TimePreferenceOlder,
}

// ParseTimePreference attempts to convert a string to a TimePreference.
func ParseTimePreference(name string) (TimePreference, error) {
	if x, ok := _TimePreferenceValue[name]; ok {
		return x, nil
	}
	return TimePreference(0), fmt.Errorf("%s is %w", name, ErrInvalidTimePreference)
}
