// Code generated by go-enum DO NOT EDIT.
// Version: v0.9.1

// Built By: go install

package main

import (
	"errors"
	"fmt"
)

const (
	// FileAccessibilityPersonal is a FileAccessibility of type Personal.
	FileAccessibilityPersonal FileAccessibility = 0
	// FileAccessibilityInternal is a FileAccessibility of type Internal.
	FileAccessibilityInternal FileAccessibility = 1
	// FileAccessibilityPublic is a FileAccessibility of type Public.
	FileAccessibilityPublic FileAccessibility = 2
)

var ErrInvalidFileAccessibility = errors.New("not a valid FileAccessibility")

const _FileAccessibilityName = "PersonalInternalPublic"

// FileAccessibilityValues returns a list of the values for FileAccessibility
func FileAccessibilityValues() []FileAccessibility {
	return []FileAccessibility{
		FileAccessibilityPersonal,
		FileAccessibilityInternal,
		FileAccessibilityPublic,
	}
}

var _FileAccessibilityMap = map[FileAccessibility]string{
	FileAccessibilityPersonal: _FileAccessibilityName[0:8],
	FileAccessibilityInternal: _FileAccessibilityName[8:16],
	FileAccessibilityPublic:   _FileAccessibilityName[16:22],
}

// String implements the Stringer interface.
func (x FileAccessibility) String() string {
	if str, ok := _FileAccessibilityMap[x]; ok {
		return str
	}
	return fmt.Sprintf("FileAccessibility(%d)", x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x FileAccessibility) IsValid() bool {
	_, ok := _FileAccessibilityMap[x]
	return ok
}

var _FileAccessibilityValue = map[string]FileAccessibility{
	_FileAccessibilityName[0:8]:   FileAccessibilityPersonal,
	_FileAccessibilityName[8:16]:  FileAccessibilityInternal,
	_FileAccessibilityName[16:22]: FileAccessibilityPublic,
}

// ParseFileAccessibility attempts to convert a string to a FileAccessibility.
func ParseFileAccessibility(name string) (FileAccessibility, error) {
	if x, ok := _FileAccessibilityValue[name]; ok {
		return x, nil
	}
	return FileAccessibility(0), fmt.Errorf("%s is %w", name, ErrInvalidFileAccessibility)
}
