// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sql-user.sql

package main

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const clearAllUserGDriveAccess = `-- name: ClearAllUserGDriveAccess :exec
UPDATE appuser
SET has_gdrive_access = FALSE
WHERE 1
`

func (q *Queries) ClearAllUserGDriveAccess(ctx context.Context) error {
	_, err := q.db.Exec(ctx, clearAllUserGDriveAccess)
	return err
}

const createUser = `-- name: CreateUser :one
INSERT INTO appuser (
  display_name,
  google_sub,
  email, 
  avatar_url,
  access_level
) VALUES (
  $1,
  $2,
  $3,
  $4,
  $5
)
RETURNING id
`

type CreateUserParams struct {
	DisplayName string
	GoogleSub   string
	Email       string
	AvatarUrl   pgtype.Text
	AccessLevel int32
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (int32, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.DisplayName,
		arg.GoogleSub,
		arg.Email,
		arg.AvatarUrl,
		arg.AccessLevel,
	)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const deleteAppuser = `-- name: DeleteAppuser :exec
DELETE
FROM appuser
WHERE id = $1
`

func (q *Queries) DeleteAppuser(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteAppuser, id)
	return err
}

const deleteAppuserLanguage = `-- name: DeleteAppuserLanguage :exec
DELETE
FROM appuser_language
WHERE appuser_id = $1
`

func (q *Queries) DeleteAppuserLanguage(ctx context.Context, appuserID int32) error {
	_, err := q.db.Exec(ctx, deleteAppuserLanguage, appuserID)
	return err
}

const deleteSessionsForUser = `-- name: DeleteSessionsForUser :exec
DELETE
FROM session
WHERE appuser_id = $1
`

func (q *Queries) DeleteSessionsForUser(ctx context.Context, appuserID int32) error {
	_, err := q.db.Exec(ctx, deleteSessionsForUser, appuserID)
	return err
}

const getAppusers = `-- name: GetAppusers :many
SELECT au.id, au.display_name, au.google_sub, au.email, au.logging_consent, au.avatar_url, au.has_gdrive_access, au.access_level, ha.home_id FROM appuser AS au
LEFT JOIN home_appuser AS ha
    ON ha.appuser_id = au.id
ORDER BY au.id
`

type GetAppusersRow struct {
	ID              int32
	DisplayName     string
	GoogleSub       string
	Email           string
	LoggingConsent  pgtype.Timestamptz
	AvatarUrl       pgtype.Text
	HasGdriveAccess bool
	AccessLevel     int32
	HomeID          pgtype.Int4
}

func (q *Queries) GetAppusers(ctx context.Context) ([]GetAppusersRow, error) {
	rows, err := q.db.Query(ctx, getAppusers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAppusersRow
	for rows.Next() {
		var i GetAppusersRow
		if err := rows.Scan(
			&i.ID,
			&i.DisplayName,
			&i.GoogleSub,
			&i.Email,
			&i.LoggingConsent,
			&i.AvatarUrl,
			&i.HasGdriveAccess,
			&i.AccessLevel,
			&i.HomeID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAppusersForHome = `-- name: GetAppusersForHome :many
SELECT au.id, au.display_name, au.google_sub, au.email, au.logging_consent, au.avatar_url, au.has_gdrive_access, au.access_level
FROM home_appuser AS hau
INNER JOIN appuser AS au
  ON hau.appuser_id = au.id
WHERE home_id = $1
`

func (q *Queries) GetAppusersForHome(ctx context.Context, homeID int32) ([]Appuser, error) {
	rows, err := q.db.Query(ctx, getAppusersForHome, homeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Appuser
	for rows.Next() {
		var i Appuser
		if err := rows.Scan(
			&i.ID,
			&i.DisplayName,
			&i.GoogleSub,
			&i.Email,
			&i.LoggingConsent,
			&i.AvatarUrl,
			&i.HasGdriveAccess,
			&i.AccessLevel,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getHomesWithDataForUser = `-- name: GetHomesWithDataForUser :many
SELECT h.id, h.name, h.capacity, h.note
FROM home AS h
INNER JOIN home_appuser AS hau
  ON hau.home_id = h.id
WHERE appuser_id = $1
`

func (q *Queries) GetHomesWithDataForUser(ctx context.Context, appuserID int32) ([]Home, error) {
	rows, err := q.db.Query(ctx, getHomesWithDataForUser, appuserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Home
	for rows.Next() {
		var i Home
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Capacity,
			&i.Note,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUser = `-- name: GetUser :one
SELECT au.id, au.display_name, au.google_sub, au.email, au.logging_consent, au.avatar_url, au.has_gdrive_access, au.access_level, COALESCE(al.language_id, 1)
FROM appuser AS au
LEFT JOIN appuser_language AS al
ON au.id = al.appuser_id
WHERE id = $1
`

type GetUserRow struct {
	ID              int32
	DisplayName     string
	GoogleSub       string
	Email           string
	LoggingConsent  pgtype.Timestamptz
	AvatarUrl       pgtype.Text
	HasGdriveAccess bool
	AccessLevel     int32
	LanguageID      int32
}

func (q *Queries) GetUser(ctx context.Context, id int32) (GetUserRow, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i GetUserRow
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.GoogleSub,
		&i.Email,
		&i.LoggingConsent,
		&i.AvatarUrl,
		&i.HasGdriveAccess,
		&i.AccessLevel,
		&i.LanguageID,
	)
	return i, err
}

const getUserIDByEmail = `-- name: GetUserIDByEmail :one
SELECT id
FROM appuser
WHERE email = $1
`

func (q *Queries) GetUserIDByEmail(ctx context.Context, email string) (int32, error) {
	row := q.db.QueryRow(ctx, getUserIDByEmail, email)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const removeHomesForAppuser = `-- name: RemoveHomesForAppuser :exec
DELETE
FROM home_appuser
WHERE appuser_id = $1
`

func (q *Queries) RemoveHomesForAppuser(ctx context.Context, appuserID int32) error {
	_, err := q.db.Exec(ctx, removeHomesForAppuser, appuserID)
	return err
}

const revokeLoggingConsent = `-- name: RevokeLoggingConsent :exec
UPDATE appuser SET logging_consent = NULL
WHERE id = $1
`

func (q *Queries) RevokeLoggingConsent(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, revokeLoggingConsent, id)
	return err
}

const scrubAppuser = `-- name: ScrubAppuser :exec
UPDATE appuser SET
  display_name = 'Deleted user (id = ' || id || ')',
  google_sub = '',
  email = '',
  logging_consent = NULL,
  avatar_url = '',
  has_gdrive_access = FALSE 
WHERE id = $1
`

func (q *Queries) ScrubAppuser(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, scrubAppuser, id)
	return err
}

const setLoggingConsent = `-- name: SetLoggingConsent :exec
UPDATE appuser SET logging_consent = NOW() + $2::INT * INTERVAL '1 day'
WHERE id = $1
`

type SetLoggingConsentParams struct {
	ID     int32
	Period int32
}

func (q *Queries) SetLoggingConsent(ctx context.Context, arg SetLoggingConsentParams) error {
	_, err := q.db.Exec(ctx, setLoggingConsent, arg.ID, arg.Period)
	return err
}

const setUserGDriveAccess = `-- name: SetUserGDriveAccess :exec
UPDATE appuser
SET has_gdrive_access = $2
WHERE id = $1
`

type SetUserGDriveAccessParams struct {
	ID              int32
	HasGdriveAccess bool
}

func (q *Queries) SetUserGDriveAccess(ctx context.Context, arg SetUserGDriveAccessParams) error {
	_, err := q.db.Exec(ctx, setUserGDriveAccess, arg.ID, arg.HasGdriveAccess)
	return err
}

const setUserLanguage = `-- name: SetUserLanguage :exec
INSERT INTO appuser_language (appuser_id, language_id)
VALUES ($1, $2)
ON CONFLICT (appuser_id) DO UPDATE
    SET language_id = EXCLUDED.language_id
`

type SetUserLanguageParams struct {
	AppuserID  int32
	LanguageID int32
}

func (q *Queries) SetUserLanguage(ctx context.Context, arg SetUserLanguageParams) error {
	_, err := q.db.Exec(ctx, setUserLanguage, arg.AppuserID, arg.LanguageID)
	return err
}

const updateUser = `-- name: UpdateUser :exec
UPDATE appuser
SET display_name = $3,
    google_sub = $4,
    avatar_url = $5
WHERE id = $1
  AND email = $2
`

type UpdateUserParams struct {
	ID          int32
	Email       string
	DisplayName string
	GoogleSub   string
	AvatarUrl   pgtype.Text
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) error {
	_, err := q.db.Exec(ctx, updateUser,
		arg.ID,
		arg.Email,
		arg.DisplayName,
		arg.GoogleSub,
		arg.AvatarUrl,
	)
	return err
}
